### ISSUE TITLE
Simplify `verify_kzg_proof()` return convention

### ISSUE THREAD

**Issue by asn-d6** [ethereum/c-kzg-4844#139]
Right now `verify_kzg_proof()` (and `verify_blob_kzg_proof()` and `verify_kzg_proof_batch()`) will return `C_KZG_RET` to indicate if the computation was finished properly, and then it will store the result of the verification in the argument `ok`.

This means that their callers should check both the `retval` and `ok` to handle verification correctly. Given the crucial importance of getting verification correctly, it might be a good idea to simplify this two-layer checking. The worst case scenario is that a user of the library thinks that `C_KZG_OK` means that verification went well.

My suggestion atm would be to merge `ok` into `retval` and make it such that `verify_kzg_proof()` returning `C_KZG_OK` denotes both a correct computation **and** also a correct verification. Then we could add another element to the enum called `C_KZG_BAD_VERIFICATION` if the caller wants to handle that case in a special way. This way the verifier just needs to check `retval` and I assume that for most clients it's gonna look like:
```
if retval == C_KZG_OK:
   accept_tx
else:
  reject_tx
```

but perhaps for others it could look like:
```
if retval == C_KZG_OK:
  accept_tx
else if retval == C_KZG_MALLOC:
  die()
else:
  reject_tx
```

It still seems simpler than the status quo.

**Comment by xrchz** [comment]
Adding another element to the enum and clarifying that `C_KZG_OK` means both no errors and successful verification where relevant sounds good to me.

**Comment by asn-d6** [comment]
Closing due to https://github.com/ethereum/c-kzg-4844/pull/158#issuecomment-1453191092
