### ISSUE TITLE
Cleanup node bindings

### ISSUE THREAD

**Issue by asn-d6** [ethereum/c-kzg-4844#149]
The node bindings (https://github.com/ethereum/c-kzg-4844/tree/main/bindings/node.js) seem to contain quite a few files and it makes it hard to review the actual code. Can we tidy them up somehow?

/cc @dgcoffman

**Comment by dgcoffman** [comment]
Each of those files serves a purpose. What tidying do you imagine? Happy to review a PR.

**Comment by asn-d6** [comment]
Will be handled as part of https://github.com/ethereum/c-kzg-4844/issues/153
