### ISSUE TITLE
free_trusted_setup should also free `s`

### ISSUE THREAD

**Issue by asn-d6** [ethereum/c-kzg-4844#172]
Is there a reason we are not also freeing the pointer `s` in `free_trusted_setup()` and the bindings need to do it themselves?

**Comment by xrchz** [comment]
We don't allocate that pointer, so it would be "rude" to free it. It's just a convention where whoever allocates a pointer is responsible for freeing it.

**Comment by asn-d6** [comment]
I see. That's because `load_trusted_setup()` takes the pointer as input instead of producing it itself.

Makes sense. Let's close this for now. Thanks!

**Comment by asn-d6** [comment]
We should check that all bindings free the pointer correctly since it's a bit counter-intuitive.
