### ISSUE TITLE
Fold in nim bindings

### ISSUE THREAD

**Issue by asn-d6** [ethereum/c-kzg-4844#173]
They currently live in https://github.com/henridf/nim-kzg-4844

This seems like a good idea so that we have everything in one place and they are also included in the auditing scope.

Some things that also need to happen:
- The bindings should implement the various required length checks (e.g. [see](https://github.com/ethereum/c-kzg-4844/blob/main/bindings/python/ckzg.c#L106) the python bindings)
- The bindings should be able to parse the yaml test vectors (see https://github.com/ethereum/c-kzg-4844/blob/main/bindings/python/tests.py)

We can perhaps add support for parsing the yaml after merging, just to get something in first.

/cc @henridf

**Comment by henridf** [comment]
Actually there's a second nim binding repo (written by @jangko) and it's likely the one we'll end up consolidating on: https://github.com/status-im/nim-kzg4844/

**Comment by asn-d6** [comment]
Done. Thanks a lot @jangko !
