### ISSUE TITLE
Update java ckzg header to new interface

### ISSUE THREAD

**Issue by jtraglia** [ethereum/c-kzg-4844#200]
This file is pretty out-of-date:

* https://github.com/ethereum/c-kzg-4844/blob/main/bindings/java/c_kzg_4844_jni.h

It says that it's a machine generated file though, not quite sure how to generate it.

https://github.com/ethereum/c-kzg-4844/blob/edb1274b705f9a44b4da0e726a16e462b76ee4b2/bindings/java/c_kzg_4844_jni.h#L1-L3

I'm surprised there are no complaints anywhere. Where is this used?

**Comment by jtraglia** [comment]
@StefanBratanov how do we regenerate this file? Or should we update it manually?

**Comment by StefanBratanov** [comment]
> @StefanBratanov how do we regenerate this file? Or should we update it manually?

You can do `javac -h . CKZG4844JNI.java` and copy the contents of it to the current header file.
