### ISSUE TITLE
Missing `verifyKzgProof` from NodeJS bindings

### ISSUE THREAD

**Issue by acolytec3** [ethereum/c-kzg-4844#22]
In the spec for EIP-4844, the point evaluation precompile has the below line
`assert verify_kzg_proof(commitment, z, y, kzg_proof)` but there is no method matching this interface exposed in the node-js bindings for this library.  It looks like it does exist in the underlying C code for `c-kzg` so could we have it added to the bindings as well so we can finish implementing the point evaluation precompile?

**Comment by xrchz** [comment]
Closed by #29
