### ISSUE TITLE
Move away from patching sha256.h?

### ISSUE THREAD

**Issue by henridf** [ethereum/c-kzg-4844#23]
The current approach to making the sha256 functions visible is to patch the header file. This works fine for bindings built via some script/make process, where patching is just a step amongst others to be executed. 

In the case of Nim however, c bindings are integrated with the regular compilation (basically, the c code is just "inlined"), so there's no good place to insert a patching step. 

For the time being I have forked this repo and added a change which [removes the patch and instead includes sha256.h](https://github.com/henridf/c-kzg-4844/commit/df76c552312f2b67291a0ac4c00760635e708ed8). Can similarly remove the patch here?

**Comment by xrchz** [comment]
Seems like a reasonable idea presuming it works :) - want to make this change as a PR?

**Comment by henridf** [comment]
Hmm, the change works fine for the purpose of the [nim bindings](https://github.com/henridf/nim-kzg-4844), but fails CI: https://github.com/henridf/c-kzg-4844/actions/runs/3677224128/jobs/6218899526

**Comment by henridf** [comment]
To clarify my above comment - I can build c_kzg_4844.o locally, without errors:

```sh
$ clang -Wall -I../inc -DFIELD_ELEMENTS_PER_BLOB=4096 -O2 -fPIC -c c_kzg_4844.c
In file included from c_kzg_4844.c:17:
In file included from ./c_kzg_4844.h:30:
In file included from ./../blst/src/sha256.h:9:
./../blst/src/vect.h:179:13: warning: unused function 'exp_mont_384' [-Wunused-function]
static void exp_mont_384(vec384 out, const vec384 inp, const byte *pow,
            ^
./../blst/src/vect.h:181:13: warning: unused function 'exp_mont_384x' [-Wunused-function]
static void exp_mont_384x(vec384x out, const vec384x inp, const byte *pow,
            ^
./../blst/src/vect.h:183:13: warning: unused function 'div_by_zz' [-Wunused-function]
static void div_by_zz(limb_t val[]);
            ^
./../blst/src/vect.h:184:13: warning: unused function 'div_by_z' [-Wunused-function]
static void div_by_z(limb_t val[]);
            ^
4 warnings generated.
```

I'm not sure why the failure occurs in CI.

**Comment by jtraglia** [comment]
Alternatively, I've made a PR to expose these functions in blst:
* https://github.com/supranational/blst/pull/146
