### ISSUE TITLE
Consider using a char buffer instead of FILE

### ISSUE THREAD

**Issue by divagant-martian** [ethereum/c-kzg-4844#276]
Using a char buffer would be IMO a more compatible version of the current api. 

Chars have a standard representation across platforms, while FILEs are a linux api that windows supports _to some degree_. The windows version of it are handles (HFILE). I see other languages are lenient on dealing with files/os paths but in general these don't exactly map since windows paths are encoded using wide chars. Under the current api we need to deal with these nuances at the ffi boundary. Using a char buffer instead we would delegate opening the file to the language implementation, and simply pass the contents to the c code

**Comment by divagant-martian** [comment]
I'm under the assumption that any bindings library should provide access to all the header functions, including reading file contents. Also, if it's important to keep the content's format uniform across bindings (which I suppose is the reason why we do this) then my proposal simply increases compatibility without losing this part

**Comment by xrchz** [comment]
I don't think the bindings libraries need to provide access to all header functions. Only the ones that are relevant for their language.

**Comment by jtraglia** [comment]
> Why not use `load_trusted_setup` instead of `load_trusted_setup_file` if you want to avoid `FILE`?

What's the benefit of using a file pointer? It's more complicated for the bindings.

**Comment by jtraglia** [comment]
Alright. I'm going to close this. I see potential complexity problems with converting UTF-8 strings to ASCII strings. I suppose it's better to let the high-level languages deal with that.
