### ISSUE TITLE
Can I just compile as a lib in C? 

### ISSUE THREAD

**Issue by winsvega** [ethereum/c-kzg-4844#288]
just make makes .a lib file with includes. but those includes does not have 
```
blob_to_kzg_commitment
compute_kzg_proof
compute_blob_kzg_proof
verify_kzg_proof
verify_blob_kzg_proof
verify_blob_kzg_proof_batch
```

**Comment by jtraglia** [comment]
Hey @winsvega, what do you mean exactly? These symbols are exported:

```
$ make c_kzg_4844.o && nm c_kzg_4844.o | grep " T "
0000000000000000 T blob_to_kzg_commitment
0000000000000760 T compute_blob_kzg_proof
00000000000002e0 T compute_kzg_proof
0000000000001fe0 T free_trusted_setup
00000000000017e0 T load_trusted_setup
0000000000001e90 T load_trusted_setup_file
00000000000008e0 T verify_blob_kzg_proof
0000000000000e80 T verify_blob_kzg_proof_batch
00000000000000a0 T verify_kzg_proof
```

Also, we generate an object file (`.o`) instead of a static library (`.a`) because it's all we require and is a little simpler, but it wouldn't be very difficult to generate a proper library instead, if that's what you want.

**Comment by winsvega** [comment]
Ah. I mean I didn't find it in include files.

**Comment by jtraglia** [comment]
Ah yeah, the header file is [here](https://github.com/ethereum/c-kzg-4844/blob/main/src/c_kzg_4844.h) and the definitions are here:

https://github.com/ethereum/c-kzg-4844/blob/fd24cf8e1e2f09a96b4e62a595b4e49f046ce6cf/src/c_kzg_4844.h#L172-L174
