### ISSUE TITLE
load_trusted_setup should take setup contents instead of setup file

### ISSUE THREAD

**Issue by dapplion** [ethereum/c-kzg-4844#3]
Current load_trusted_setup implementation takes a file as input

https://github.com/ethereum/c-kzg-4844/blob/9611bfde9ab47366bfdc1d2cc0ea388bda1f502e/src/c_kzg_4844.c#L773

To support browser light-clients we'll compile c-kzg to WASM, which would require no interaction with the file system. It would also make DX more flexible on how client implementations want to handle the trusted setup loading.

This was discussed offline in a chat and agreed to adopt a simple serialization format for the trusted setup. Just concat the point count and the serialized points in the following order.
```
G1Count | G2Count | [G1] | [G2]
```

**Comment by xrchz** [comment]
What's the proposed type for the input? `uint8_t*`?

**Comment by dapplion** [comment]
> What's the proposed type for the input? uint8_t*?

We didn't discuss the specific types, so up to you what makes more sense

**Comment by StefanBratanov** [comment]
Is it a good idea to support both and then clients can choose either?

**Comment by pawanjay176** [comment]
Would prefer having this method as well. Having a hardcoded file format doesn't give us a lot of flexibility in choosing our own formats for specifying the trusted setup params. For e.g. the trusted setup defined [here](https://github.com/ethereum/consensus-specs/tree/dev/presets/mainnet/trusted_setups) is in json. We could also potentially have test vectors having the trusted setup in different formats.

This could be the interface potentially
```c
C_KZG_RET load_trusted_setup(KZGSettings *out,
    size_t g1_len,
    size_t g2_len,
    uint8_t[48] *g1_values,
    uint8_t[96] *g2_values,
);
```

The `g1_values` and `g2_values` are arrays of 48 byte and 96 byte arrays respectively. Sorry if my C code doesn't actually represent that :sweat_smile:

**Comment by dapplion** [comment]
> 
> This could be the interface potentially
> 
> ```c
> C_KZG_RET load_trusted_setup(KZGSettings *out,
>     size_t g1_len,
>     size_t g2_len,
>     uint8_t[48] *g1_values,
>     uint8_t[96] *g2_values,
> );
> ```
> 
> The `g1_values` and `g2_values` are arrays of 48 byte and 96 byte arrays respectively. Sorry if my C code doesn't actually represent that sweat_smile

This interface would work fine for me too :+1: requires some extra work on the bindings, but it's fine. Whatever gets rid of this cursed file API the fastest :rofl:

**Comment by xrchz** [comment]
Does #24 look good for this?

**Comment by dapplion** [comment]
> Does #24 look good for this?

Looks good yes!
