### ISSUE TITLE
Segfault in computeAggregateKzgProof with invalid blob

### ISSUE THREAD

**Issue by jtraglia** [ethereum/c-kzg-4844#30]
This may only pertain to the Java bindings for this function.

If a zero-length blob is passed to `computeAggregateKzgProof` it will cause a segmentation fault. The problem is that this is allowed. I know that a blob should be 32 bytes, but the method allows arbitrary `byte[]` types without length constraints.

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x0000000103059330, pid=53565, tid=5891
#
# JRE version: OpenJDK Runtime Environment Homebrew (11.0.16.1) (build 11.0.16.1+0)
# Java VM: OpenJDK 64-Bit Server VM Homebrew (11.0.16.1+0, mixed mode, tiered, compressed oops, g1 gc, bsd-aarch64)
# Problematic frame:
# C  [libckzg4844jni.dylib+0x21330]  blst_scalar_from_lendian+0x8
#
```

Excerpt of the stack trace:

```
C  [libckzg4844jni.dylib+0x21330]  blst_scalar_from_lendian+0x8
C  [libckzg4844jni.dylib+0x39a8]  Java_ethereum_ckzg4844_CKZG4844JNI_computeAggregateKzgProof+0x68
j  ethereum.ckzg4844.CKZG4844JNI.computeAggregateKzgProof([BJ)[B+0
j  tech.pegasys.teku.kzg.ckzg4844.CKZG4844.computeAggregateKzgProof(Ljava/util/List;)Ltech/pegasys/teku/kzg/KZGProof;+13
j  tech.pegasys.teku.kzg.ckzg4844.CKZG4844PropertyTest.computeAggregateKzgProofThrowsExpected(Ljava/util/List;)V+11
v  ~StubRoutines::call_stub
V  [libjvm.dylib+0x32ffa8]  JavaCalls::call_helper(JavaValue*, methodHandle const&, JavaCallArguments*, Thread*)+0x2e0
V  [libjvm.dylib+0x5d60c0]  invoke(InstanceKlass*, methodHandle const&, Handle, bool, objArrayHandle, BasicType, objArrayHandle, bool, Thread*)+0x76c
V  [libjvm.dylib+0x5d58f8]  Reflection::invoke_method(oopDesc*, Handle, objArrayHandle, Thread*)+0x114
V  [libjvm.dylib+0x3c2350]  JVM_InvokeMethod+0x210
```

`compute_aggregate_kzg_proof` calls `poly_from_blob`:

https://github.com/ethereum/c-kzg-4844/blob/130b629d4cd4bf0411e0cba9056a6759545a94a9/src/c_kzg_4844.c#L1202-L1205

`poly_from_blob` calls `bytes_to_bls_field`:

https://github.com/ethereum/c-kzg-4844/blob/130b629d4cd4bf0411e0cba9056a6759545a94a9/src/c_kzg_4844.c#L934-L938

`bytes_to_bls_field` calls `blst_scalar_from_lendian`:

https://github.com/ethereum/c-kzg-4844/blob/130b629d4cd4bf0411e0cba9056a6759545a94a9/src/c_kzg_4844.c#L849-L855

Associated with:

* https://github.com/ConsenSys/teku/pull/6596

**Comment by StefanBratanov** [comment]
Hey :) I am tracking this here as well: https://github.com/ConsenSys/jc-kzg-4844/issues/7

I ran into these issues as well and as a workaround started throwing an exception for 0 length blobs but ideally would like to find a solution.

**Comment by jtraglia** [comment]
Ah nice. Glad to see that it was a known issue.

**Comment by xrchz** [comment]
Does #40 affect this?

**Comment by jtraglia** [comment]
> Does #40 affect this?

I believe it's actually in response to this different issue:

* https://github.com/ConsenSys/teku/issues/6622

**Comment by StefanBratanov** [comment]
So, still observing segfaults for the following scenarios, which should in practice never happen, but would rather get C_KZG_BADARGS:

`blob_to_kzg_commitment` : Passing an array of length 0 for blob
`computeAggregateKzgProof` : Passing an array of length 0 for blobs and n > 0
`verifyAggregateKzgProof` : Passing an array of length 0 for blobs and n > 0

**Comment by benjaminion** [comment]
> `blob_to_kzg_commitment` : Passing an array of length 0 for blob

C has no inherent concept of array length at run time. A blob is always `FIELD_ELEMENTS_PER_BLOB * BYTES_PER_FIELD_ELEMENT` bytes long. This should be checked in the bindings and handled there.

> `computeAggregateKzgProof `: Passing an array of length 0 for blobs and n > 0
> `verifyAggregateKzgProof `: Passing an array of length 0 for blobs and n > 0

The only information C has about the array length is the value of `n` that you pass - it has no way to check its correctness. Again, this should be checked for and handled in the bindings.

**Comment by StefanBratanov** [comment]
> > `blob_to_kzg_commitment` : Passing an array of length 0 for blob
> 
> C has no inherent concept of array length at run time. A blob is always `FIELD_ELEMENTS_PER_BLOB * BYTES_PER_FIELD_ELEMENT` bytes long. This should be checked in the bindings and handled there.
> 
> > `computeAggregateKzgProof `: Passing an array of length 0 for blobs and n > 0
> > `verifyAggregateKzgProof `: Passing an array of length 0 for blobs and n > 0
> 
> The only information C has about the array length is the value of `n` that you pass - it has no way to check its correctness. Again, this should be checked for and handled in the bindings.

Thanks Ben. But this happens only when passing 0 length blobs (`new byte[0]` in Java) for the methods above. Passing even `new byte[1]` does not cause segfaults without any handling in the binding.

**Comment by benjaminion** [comment]
Probably something like this going on.

When you pass an array of length 1 from Java then the OS has allocated a page for the contents, so when C tries to access it there will be no segmentation violation: the memory locations are valid addresses even though most of the blob data will be junk. C will just keep reading past the end of the array you passed, but the memory is "valid" in the sense that the OS knows about it.

When you pass an array length zero, there is probably no page allocated - the pointer to the start of the array points somewhere invalid - so when C tries to read the memory it gets a segmentation violation.

There's nothing that can be done about this on the C side - it can only try to read the Blob from the pointer it is given, and cannot check whether the memory location is valid or invalid. Checking that the passed Blob data is the correct length must be done outside the c-kzg-4844 library, ideally in the bindings.

**Comment by StefanBratanov** [comment]
Had a discussion with Ben. Will tackle this issue in a PR soon. Will change the java binding.
