### ISSUE TITLE
Add library prefix to all ckzg symbols

### ISSUE THREAD

**Issue by michaelsproul** [ethereum/c-kzg-4844#312]
Currently the `c-kzg` library uses `#define` constants for the mainnet/minimal paramaters like `FIELD_ELEMENTS_PER_BLOB`:

https://github.com/ethereum/c-kzg-4844/blob/cfdd9e5f8f6fa4375034733ad06cb9d1030a0fd9/src/c_kzg_4844.h#L39-L43

This makes it _very hard_ (but not impossible*) to link two copies of the library to enable switching between mainnet and minimal configurations at runtime.

*My attempt at doing this is documented here: https://github.com/sigp/lighthouse/pull/4276. I had to use `objcopy` to rename `c-kzg`'s symbols so that they wouldn't conflict. Needless to say this is not a sensible approach to take.

To do this better I was thinking the library could accept _another_ `#define` constant which it prepends to all symbol names. Then the downstream consumer of the library could easily avoid collisions, with names like `ckzg_blob_to_kzg_commitment` and `ckzgmin_blob_to_kzg_commitment` instead of just `blob_to_kzg_commitment`. The `ckzg` prefix could be the default if no prefix is specified.

**Comment by divagant-martian** [comment]
digging this approach :tada:

**Comment by asn-d6** [comment]
So, I pushed https://github.com/ethereum/c-kzg-4844/pull/313 which includes some cursed macro code https://github.com/ethereum/c-kzg-4844/pull/313/commits/2c58b2aa539eba743ae3a07939fa2e9df55933c5 that gets used around the codebase https://github.com/ethereum/c-kzg-4844/pull/313/commits/62537515f4e00b07d85a89d84b9aeeee9140b2ee .

To use this cursed feature you need to define a `LIB_PREFIX` as follows: `LIB_PREFIX=ckzg`

Would this work for you guys?

Either way, I think we should probably wait until Justin is back from OOO to see if this is acceptable in terms of code quality. I don't really like it, but if it's a needed feature I can probably turn a blind eye.

**Comment by michaelsproul** [comment]
@asn-d6 That looks like it would work for us, and I don't think the macros are _too bad_ from an aesthetics/maintainability PoV. If I get some time I'll try to re-work the Rust bindings and confirm that it works end-to-end.

Thanks for your work on that!

**Comment by ppopth** [comment]
> Either way, I think we should probably wait until Justin is back from OOO to see if this is acceptable in terms of code quality. I don't really like it, but if it's a needed feature I can probably turn a blind eye.

Yeah, let's wait for his comment, but I think the PR already looks good.

**Comment by jtraglia** [comment]
> > Either way, I think we should probably wait until Justin is back from OOO to see if this is acceptable in terms of code quality. I don't really like it, but if it's a needed feature I can probably turn a blind eye.
> 
> Yeah, let's wait for his comment, but I think the PR already looks good.

Reviewed the PR yesterday. I'm not ecstatic about it either, but I think it's a clever solution with minimal changes. I want to look into how complicated it would be to do it "properly". Maybe we do it this way now & the complicated way later.

**Comment by jtraglia** [comment]
Fixed in #317. Closing.
