### ISSUE TITLE
Broken CI in rust-windows because of rust-1.7.0

### ISSUE THREAD

**Issue by asn-d6** [ethereum/c-kzg-4844#318]
See https://github.com/ethereum/c-kzg-4844/pull/311#issuecomment-1582439003

**Comment by jtraglia** [comment]
Temporarily fixed/masked the problem with this PR:

* https://github.com/ethereum/c-kzg-4844/pull/322

When there's a new release of rust/criterion that fixes the problem, please revert that PR.
