### ISSUE TITLE
Expose `compute_kzg_proof` in interface

### ISSUE THREAD

**Issue by dankrad** [ethereum/c-kzg-4844#34]
I suggest adding `compute_kzg_proof` to the interface as it is required in order to compute valid inputs to the point evaluation precompile.

It will also be useful for testing purposes (easier to generate test cases for point evaluation precompile).

**Comment by xrchz** [comment]
Should it also be marked as a "Public method" in https://github.com/ethereum/consensus-specs/blob/dev/specs/eip4844/polynomial-commitments.md?

**Comment by dankrad** [comment]
> Should it also be marked as a "Public method" in https://github.com/ethereum/consensus-specs/blob/dev/specs/eip4844/polynomial-commitments.md?

Yes I think we should. Good point.

**Comment by xrchz** [comment]
After #27 is resolved, how should we handle the `BLSFieldElement` argument to `compute_kzg_proof`? Would `Bytes32` be ok even though this differs from the spec (`uint256` -- not a native C type)?

**Comment by dankrad** [comment]
Yeah I guess Bytes32 is the most consistent with how we are handling all the other cases.
