### ISSUE TITLE
Nodejs does not support browsers

### ISSUE THREAD

**Issue by iteyelmp** [ethereum/c-kzg-4844#343]
Node.js uses the 'fs' and 'path' modules that are not supported in the browser, can it be changed to pass the data of the file?
<img width="363" alt="image" src="https://github.com/ethereum/c-kzg-4844/assets/6647261/0d3062b1-caa9-4869-a3f3-9420c16e3f52">

**Comment by iteyelmp** [comment]
It looks like .node files are also not supported and need to be compiled to wasm.

**Comment by jtraglia** [comment]
Yes, this is a known limitation. @matthewkeil & @g11tech would know more. How difficult would it be to support browsers?

**Comment by ququzone** [comment]
> If we have a wasm c-kzg build we can make the c-kzg browser complaint , so that I think would be the primary workitem here.

Does `c-kzg rust bindings` support compile to wasm32? I tried many ways, but they all failed. 😢

**Comment by asn-d6** [comment]
Closing stale tickets. Feel free to reopen if needed.
