### ISSUE TITLE
Rust build.rs: Pass -D__BLST_NO_ASM__ on non-x86-64/non-aarch64 ISAs

### ISSUE THREAD

**Issue by mratsim** [ethereum/c-kzg-4844#398]
The current build.rs does not pass the -D__BLST_NO_ASM__ flag when compiling for non-x86-64 / non-aarch64 ISAs.

https://github.com/supranational/blst/blob/0d46eefa45fc1e57aceb42bba0e84eab3a7a9725/build.sh#L91-L93

This is impacting zkVMs that target other ISAs like Risc-V, WASM, MIPS or plain LLVM IR.

Note: ultimately zkVMs will optimize blob proof verification using:
- https://notes.ethereum.org/@vbuterin/proto_danksharding_faq#Moderate-approach-works-with-any-ZK-SNARK
- and https://notes.ethereum.org/@dankrad/kzg_commitments_in_proofs

but this will still be helpful for testing and benchmarking.

**Comment by jtraglia** [comment]
Hey @mratsim, is this problem specific to the Rust bindings? Would you be willing to make a PR for this?

**Comment by jtraglia** [comment]
Hey again. I made a quick PR which I think will handle this. Do you have a system to test this with?

**Comment by mratsim** [comment]
Other platforms might also need something similar if they use a package manager and integrate building C libraries, like Go and Nim.

I will make a PR.

**Comment by jtraglia** [comment]
Thanks for the response. Sounds good, keep us updated. I will close #399.

**Comment by jtraglia** [comment]
Hey @mratsim any updates on this?

**Comment by mratsim** [comment]
This is worked on at zkVM-level. Closing.
