### ISSUE TITLE
Blob value in argument to context.VerifyBlobKZGProof

### ISSUE THREAD

**Issue by ersanyakit** [ethereum/c-kzg-4844#410]
github.com/ethereum/go-ethereum/crypto/kzg4844
../../../../go/pkg/mod/github.com/ethereum/go-ethereum@v1.13.14/crypto/kzg4844/kzg4844_gokzg.go:52:49: cannot use (gokzg4844.Blob)(blob) (value of type gokzg4844.Blob) as *gokzg4844.Blob value in argument to context.BlobToKZGCommitment
../../../../go/pkg/mod/github.com/ethereum/go-ethereum@v1.13.14/crypto/kzg4844/kzg4844_gokzg.go:64:47: cannot use (gokzg4844.Blob)(blob) (value of type gokzg4844.Blob) as *gokzg4844.Blob value in argument to context.ComputeKZGProof
../../../../go/pkg/mod/github.com/ethereum/go-ethereum@v1.13.14/crypto/kzg4844/kzg4844_gokzg.go:86:44: cannot use (gokzg4844.Blob)(blob) (value of type gokzg4844.Blob) as *gokzg4844.Blob value in argument to context.ComputeBlobKZGProof
../../../../go/pkg/mod/github.com/ethereum/go-ethereum@v1.13.14/crypto/kzg4844/kzg4844_gokzg.go:97:36: cannot use (gokzg4844.Blob)(blob) (value of type gokzg4844.Blob) as *gokzg4844.Blob value in argument to context.VerifyBlobKZGProof

**Comment by jtraglia** [comment]
Hi there. This is for go-kzg-4844, which is a different project.

https://github.com/crate-crypto/go-kzg-4844
