### ISSUE TITLE
no pypi source packages

### ISSUE THREAD

**Issue by step21** [ethereum/c-kzg-4844#414]
Hi,

is there a particular reason why no source packages are uploaded to pypi? (https://pypi.org/project/ckzg/0.4.3/#files)
Especially for generating conda-forge packages or other distributions, a stable source like pypi that is not github packages would be preferred. Is there any chance that could be added? I might be able to assist with a PR, depending on what kind of build system you use.

**Comment by jtraglia** [comment]
Hey @step21, there's no particular reason. We've only just recently started to publish to pypi. Probably just an oversight on our part. I'd be very welcome to a PR which updates our release workflow to include source distributions. 

Please see this file: https://github.com/ethereum/c-kzg-4844/blob/main/.github/workflows/python-release.yml

**Comment by step21** [comment]
Please see this PR https://github.com/ethereum/c-kzg-4844/pull/415
