### ISSUE TITLE
Publish `v1.0.1` Rust bindings to `crates.io`

### ISSUE THREAD

**Issue by ralexstokes** [ethereum/c-kzg-4844#425]
It looks like they are missing, and it would simplify some of the build process if it was available.

**Comment by jtraglia** [comment]
Hey @ralexstokes, yeah that's my fault. I forgot to update the version from v1.0.0 to v1.0.1 in Cargo.toml, so we were unable to publish the new version. I've been waiting for enough changes to justify a new v1.0.2 release. We've made some improvements to the nodejs bindings recently, so I'll push for a new release this upcoming week.

**Comment by jtraglia** [comment]
@ralexstokes we just made the v1.0.2 release. I've pinged @Rjected about publishing the Rust package.

**Comment by ralexstokes** [comment]
great thanks! I've had to maintain patches to work around not having the build script fix in v1.0.1 so will be glad once users update :)

**Comment by jtraglia** [comment]
@ralexstokes here's the link: https://crates.io/crates/c-kzg/1.0.2
