### ISSUE TITLE
Electra Tasklist

### ISSUE THREAD

**Issue by jtraglia** [ethereum/c-kzg-4844#436]
### Easy

- [x] Add 7594 functions to README
- [x] Update blst to [v0.3.12](https://github.com/supranational/blst/releases/tag/v0.3.12)
- [x] Replace fuzz with rustfuzz
- [x] Update copyright year in C files
- [x] In Rust bindings, change `load_trusted_setup` params to `&[u8]`
- [x] Update repository description
- [x] Add CI check to ensure reference tests are up-to-date
- [x] Add makefile at project's root which builds/tests everything
- [x] Replace `s->max_width` with `FIELD_ELEMENTS_PER_EXT_BLOB`
- [x] Where possible, replace `uint64_t` with `size_t`
- [x] But use `uint64_t` instead of `size_t` for public API parameters
- [x] ~~Be consistent with "KZG" vs "Kzg"~~
- [x] Use `IEnumerable` generator in C#'s 4844 test functions

### Moderate

- [x] Change `num_g*_points` to `num_g*_bytes` in `load_trusted_setup`
- [x] Decide if we want to keep individual proof recovery
- [x] ~~Add benchmarks for bindings with benchmarks (Go, Java, Rust)~~
- [x] Add EIP-4844 fuzzers to rustfuzz
- [x] Get rid of the `poly_t` type in C code
- [x] ~~Rename `KzgSettings` to `KzgContext`~~
- [x] ~~Add more specific error types~~
- [x] Add new profiling functions for 7594 functions
- [x] Change column limit for C code to 100 (maybe 120) characters
- [x] Merge das branch into main
- [x] Clean up `KZGSettings` structure
- [x] ~~Replace Makefile coverage with Rust coverage (instructions)~~
- [x] Make a v2 release

### Hard

- [x] Review recovery code and improve documentation
- [x] ~~Document new individual proof recovery code~~
- [x] ~~Rename c-kzg-4844 so it's clear it handles more than EIP-4844~~
- [x] Split `c_kzg_4844.c` into multiple C files; distinction between 4844 and 7594
- [x] Look into not requiring flattened arrays; easier for clients
- [x] Activate internal players (Gotti, Benedikt, Antonio) to do private audits

**Comment by asn-d6** [comment]
Adding another one:
- Refactor recovery to use coset FFT (https://github.com/ethereum/consensus-specs/pull/3781)

**Comment by jtraglia** [comment]
Released v2.0.0 for Electra. Closing.
