### ISSUE TITLE
Documentation of KZGSettings (Branch `das`)

### ISSUE THREAD

**Issue by b-wagn** [ethereum/c-kzg-4844#439]
Note: this issue is about [this](https://github.com/ethereum/c-kzg-4844/tree/das) branch.

When reading the code, I felt that the different fields related to roots of unity in `KZGSettings` ([here](https://github.com/ethereum/c-kzg-4844/blob/das/src/c_kzg_4844.h#L159)) are a bit confusing.
This includes the fields `roots_of_unity`, `expanded_roots_of_unity`, and `reverse_roots_of_unity`.

As a result, it is a bit hard to understand code that uses these fields, or to modify code properly if needed.
For example, here are some questions that I can not immediately resolve from the documentation.
A better documentation and more consistent naming could help to identify what they are.
The main questions that the comments/naming should address for each field are the following:

* Is the field related to a blob or to an extended blob?
* How long is the field, i.e., how many elements does it contain?
* Are these roots in reverse bit ordering or not?

**Comment by patniemeyer** [comment]
FYI on the documentation topic - I wrote a short, developer-level article that shows how to use the ckzg libs from Python and walks through the nature and the sizes of the datatypes (how to chunk the data) including how to use the roots of unity from KZGSettings to address your data elements.  If it is useful it could be expanded upon and turned into documentation.  Link:  [https://pat.net/ckzg/](https://pat.net/ckzg/)

**Comment by asn-d6** [comment]
@b-wagn fixed the big issues with the roots of unity in https://github.com/ethereum/c-kzg-4844/pull/467.
There were a few additional concerns with the `KZGSettings` fields raised in the PR. Feel free to take a stab at them if you would like.

For now, I'm closing this issue. But feel free to open a new one with more specific tasks.
