### ISSUE TITLE
Optimise polynomial evaluation

### ISSUE THREAD

**Issue by xrchz** [ethereum/c-kzg-4844#53]
Copying an idea of @asn-d6's from chat:

> 
> you can avoid a needless non-batched bls_modular_inverse in evaluate_polynomial_in_evaluation_form() by computing and caching inverse_width at boot time. then you wouldn't need:
> 
>   fr_from_uint64(&tmp, FIELD_ELEMENTS_PER_BLOB);
>   fr_div(out, out, &tmp);
> 
> and you could replace it with a multiplication by inverse_width instead

**Comment by asn-d6** [comment]
Closing this given the tiny benefit. Let's revisit if we need to hyperoptimize the barycentric.

**Comment by asn-d6** [comment]
I guess it seems like I don't have the powers to close this :D
