### ISSUE TITLE
Java/node bindings: Insufficient validation of inputs to `verify_aggregate_kzg_proof()`

### ISSUE THREAD

**Issue by asn-d6** [ethereum/c-kzg-4844#63]
The c-kzg public method `verify_aggregate_kzg_proof()` expects that its `blobs` and `expected_kzg_commitments` arguments have length of size `n`.

This is an undocumented requirement but still real because of the array accessing loop in https://github.com/ethereum/c-kzg-4844/blob/c72ea8e1dcafa0254bac02b2f813fc8042686f05/src/c_kzg_4844.c#L1290-L1294

However, this is not respected by all bindings:
- The Java bindings do not check that there are `count` commitments present
- The nodejs bindings assume that there are as many commitments as blobs and then freely copy memory into the short `commitments[blob_index]` array

I suggest we document this requirement in the core c-kzg library so that bindings know what to expect. We also need to fix the above two cases. We might also need some unittests that check this behavior.

**Comment by asn-d6** [comment]
For additional context here, the caller of `verify_aggregate_kzg_proof()`  makes sure that commitments and blobs have the same size: https://github.com/ethereum/consensus-specs/blob/dev/specs/eip4844/fork-choice.md#validate_blobs_sidecar

It might be worth highlighting that invariant in the bindings by adding an assert.

**Comment by xrchz** [comment]
I think this is all done by #68

**Comment by xrchz** [comment]
Oh maybe the node bindings are still not done?

**Comment by dgcoffman** [comment]
I can add a check in the Node bindings
