### ISSUE TITLE
NULL checks before free() unnecessary

### ISSUE THREAD

**Issue by xrchz** [ethereum/c-kzg-4844#66]
`free(NULL)` is a no-op, so we can simplify code that currently looks like `if (ptr != NULL) free(ptr);` to `free(ptr);`

See e.g. https://stackoverflow.com/questions/1938735/does-freeptr-where-ptr-is-null-corrupt-memory

**Comment by jtraglia** [comment]
Good idea. I wasn't certain that was portable, but it is. This would be cleaner 👍

**Comment by asn-d6** [comment]
I like this.

Talking about malloc hygiene -- and sorta hjiacking this thread as well -- something cool that Tor does is that it has a `tor_free()` macro that sets the pointer to NULL after freeing it: https://github.com/torproject/tor/blob/main/src/lib/malloc/malloc.h#L34

This makes it much harder to double free things. I was thinking of porting this to c-kzg.
