### ISSUE TITLE
Add function documentation comments

### ISSUE THREAD

**Issue by jtraglia** [ethereum/c-kzg-4844#67]
Some of the functions (mostly towards the bottom of the source file) are lacking documentation (doxygen) comments. I think it would be a good idea for someone to add these. Especially for the public/exported functions, but ideally all functions. I would do this myself, but I don't feel qualified to write these comments.

**Comment by xrchz** [comment]
We don't actually use doxygen any more - would more streamlined comments possibly be better? Or maybe we should actually use doxygen?

**Comment by jtraglia** [comment]
So I prefer the doxygen style. It's what makes most sense to me.

**Comment by asn-d6** [comment]
Here is a start https://github.com/ethereum/c-kzg-4844/pull/79

**Comment by xrchz** [comment]
Every function looks documented to me currently, so closing.
