### ISSUE TITLE
Include subgroup checks when deserialising points

### ISSUE THREAD

**Issue by kevaundray** [ethereum/c-kzg-4844#84]
Checking the code here : https://github.com/ethereum/c-kzg-4844/blob/main/src/c_kzg_4844.c#L498 It seems that we are not checking whether points are in the subgroup and are just checking whether points are in the group.

**Comment by xrchz** [comment]
Is there a test we could add to one of the bindings that would expose this issue?

**Comment by asn-d6** [comment]
Yes we should figure out if we can add a test.

**Comment by asn-d6** [comment]
This is kinda what we are looking for https://github.com/ethereum/bls12-381-tests/blob/master/main.py#L599

**Comment by asn-d6** [comment]
We added unittests for this in https://github.com/ethereum/c-kzg-4844/pull/102

**Comment by xrchz** [comment]
So we can close this now right? I will close but reopen/message me if incorrect.
